### ISSUE TITLE
Extended link syntax

### ISSUE THREAD

**Issue by cdfhalle** [hpi-swa-teaching/MarkdownEditor#119]
As a user I want to use the Markdown link-syntax that contains only the link itself to be able to write links more intuitively and integrate links with brackets in it.

The mentioned link syntax:
```
<http://www.example.com>
```
The result:
http://www.example.com

**Comment by lucasliebe** [comment]
Wouldnt it be better to use one of the other syntaxes since we are missing tokens for this it might be hard or slow to recognize
