### ISSUE TITLE
Broken inline text styling

### ISSUE THREAD

**Issue by cdfhalle** [hpi-swa-teaching/MarkdownEditor#121]
To get the text from a `MarkdownBlock` the method asText is called. In the most cases the method looks like this:
```
asText

	| text |
	text := self content asText.
        self styler privateStyle: text.
	self addAttributesTo: text.
	^ text
```
Since `addAttributesTo:` also sets the color and font attributes it simply overwrites the attributes set by the call of `privateStyle:`.
This is also the reason why links are not colored blue and raises the question whether the color of links should always be blue or should match the color of the paragraphs.

**Comment by JulianEgbert** [comment]
What about leaving them in the color that is set in the settings and **Underline** them? This would be unique, because MD doesn't support underlining for default text.
