### ISSUE TITLE
Outline for document

### ISSUE THREAD

**Issue by ghost** [hpi-swa-teaching/MarkdownEditor#139]
As a **scientist writing papers in Markdown / as a student taking notes in Markdown** I want to be able to **generate an outline** of my document in order to get a **better overview of headings and subheadings.**

**Comment by JulianEgbert** [comment]
Is this like `\tableofcontents` in LaTeX?

**Comment by JulianEgbert** [comment]
The outline will be generated in an external window and can then be copied into the document.

**Comment by lucasliebe** [comment]
already done in other issue
