### ISSUE TITLE
Support for HTML comments

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-teaching/MarkdownEditor#16]
As a frequent user of the markdown editor I rely a lot on HTML comments to add context information to my documents which are however not relevant to the content of the document itself. Thus, I would like to have that syntax supported in some way. 

(Is this the right place for this issue?)

**Comment by felix-gohla** [comment]
Would you like them to be highlighted by a color in some way or do you have another preference for displaying HTML comments?

**Comment by codeZeilen** [comment]
I would prefer a pale color as highlighting. I would not expect another form of highlighting beyond that.

**Comment by jonaskordt** [comment]
Now merged into master. 💃
