### ISSUE TITLE
Specific font sizes as preferences

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-teaching/MarkdownEditor#17]
This is more of a proposal, as I don't know whether it is actually a good idea: How about allowing users to set the particular font sizes which are used for the headings as a preference? Or: Something that can be changed for every workspace? Or: just a factor of the font size set for the whole document?

The reason I am bringing this up is, that the first thing I did after starting to use the editor was changing the hard coded font sizes to something smaller :)

**Comment by felix-gohla** [comment]
Closed because user can easily edit the font sizes in `MarkdownHeading>>fontSizes`.
