### ISSUE TITLE
Simplify attributes

### ISSUE THREAD

**Issue by pixunil** [hpi-swa-teaching/MarkdownEditor#18]
`MarkdownAttribute` has support for a collection of `TextAttribute`, where we only will use one per object. Thus, it should become a single value.

Also, it has two subclasses which only differ in their value. This should be refactored into a variable in a single class.

**Comment by jonaskordt** [comment]
The subclass shall be removed. For this we need an instance variable in for the superclass which contains the text attribute. Create convenience instance creators `MarkdownAttribute>>bold` and `MarkdownAttribute>>italic`.
