### ISSUE TITLE
Code duplication in TestCase accessors

### ISSUE THREAD

**Issue by jonaskordt** [hpi-swa-teaching/MarkdownEditor#28]
Some accessors in the `TestCase` subclasses are used by multiple subclasses. This produces code duplication.

Solution: Create a `TestCase` subclass which implements those accessors and let the other subclasses inherit that implementation.

**Comment by felix-gohla** [comment]
The following classes are affected: `MarkdownHeadingTest`, `MarkdownBlockStylerTest` (headingFontSized), `MarkdownBlockTextStyler`, `MarkdownInlineTextStyler`, `MarkdownCommentBlock` (`...areStyleOf:` and `attributesOf:`).
