### ISSUE TITLE
Support für neuere Squeak-Versionen

### ISSUE THREAD

**Issue by martin-schilling** [hpi-swa-teaching/MarkdownEditor#39]
* [ ] Squeak64-trunk on ubuntu-latest
* [ ] Squeak64-5.3 on ubuntu-latest
* [ ] Squeak64-trunk on macos-latest
* [ ] Squeak64-5.3 on macos-latest

Schätzung: 15

**Comment by MaximilianKleissl** [comment]
Kann dieses Issue geschlossen werden? Die Karte im Projekt gilt ja als vom Kunden abgenommen.
