### ISSUE TITLE
[OLD] Replacing Delimiter with String Token

### ISSUE THREAD

**Issue by jonaskordt** [hpi-swa-teaching/MarkdownEditor#5]
Class: `MarkdownInlineParser`
Problem: Code Duplication (`cutCloser:to:`, `cutOpener:to:`, `removeDelimitersBetween:and:`)

Proposed solution: create a new method called `convertToStringToken: aMarkdownToken` which replaces the `aMarkdownToken` with its version as a `MarkdownString` and return the converted version.

**Comment by JulianEgbert** [comment]
Not relevant anymore due to the new parser
