### ISSUE TITLE
Font size will bump while typing

### ISSUE THREAD

**Issue by pixunil** [hpi-swa-teaching/MarkdownEditor#6]
### Steps to reproduce
1. Type `# H1` to achieve a heading with big font size.
2. Use the arrow keys <kbd>←</kbd> followed by <kbd>→</kbd> to infect the state.
3. Type in a new line a paragraph.
    _You should notice that the characters are typed big and will shrink after a short time to their normal size._

### Research
The `SmalltalkEditor`, which is used as default for text morphs saves its last seen emphasis into `emphasisHere`. Through the toggling, this variable will contain the emphasis for a heading and won't reset when typing the paragraph.

**Comment by felix-gohla** [comment]
This could be fixed by having custom `TextAttribute`s. When we would create a class `MarkdownFontReference` (or so), we can overwrite `mayBeExtended` to return `false`. Then the glitches wouldn't be that obvious to notice.
